### ISSUE TITLE
Fatal error in QM_Output_Html_Assets::get_dependency_data

### ISSUE THREAD

**Issue by tomjn** [johnbillion/query-monitor#387]
I'm unsure how this happened but I found it in my error logs, in v3.2.2:

```
Fatal error: Uncaught TypeError: Argument 1 passed to QM_Output_Html_Assets::get_dependency_data() must be an instance of _WP_Dependency, boolean given, called in /srv/www/tomjn.com/htdocs/wp-content/plugins/query-monitor/output/html/assets.php on line 149 and defined in /srv/www/tomjn.com/htdocs/wp-content/plugins/query-monitor/output/html/assets.php:175
Stack trace:
#0 /srv/www/tomjn.com/htdocs/wp-content/plugins/query-monitor/output/html/assets.php(149): QM_Output_Html_Assets->get_dependency_data(false, Object(WP_Styles), 'styles')
#1 /srv/www/tomjn.com/htdocs/wp-content/plugins/query-monitor/output/html/assets.php(119): QM_Output_Html_Assets->dependency_rows(Array, Object(WP_Styles), 'Footer', 'styles')
#2 /srv/www/tomjn.com/htdocs/wp-content/plugins/query-monitor/dispatchers/Html.php(197): QM_Output_Html_Assets->output()
#3 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): QM_Dispatcher_Html->dispatch('')
#4 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
in /srv/www/tomjn.com/htdocs/wp-content/plugins/query-monitor/output/html/assets.php on line 175
```

**Comment by johnbillion** [comment]
IIRC this can happen when a plugin deregisters a script very late on in the page load.

Can you narrow down which plugin or theme is causing the error to appear? Does the error appear more than once?

**Comment by johnbillion** [comment]
Are you able to try out the `develop` branch of QM? I've refactored this entire panel, but the issue might still appear.

**Comment by tomjn** [comment]
hmmm this is in production so I'm not keen on installing node/npm/grunt/etc to build the `develop` branch.

To reproduce, I have this mu-plugin:

```php
<?php

add_filter( 'jetpack_implode_frontend_css', '__return_false' );

add_action('wp_print_styles', 'tomjn_filter_scripts', 1000000);
add_action('wp_print_footer_scripts',  'tomjn_filter_scripts', 1000000);

function tomjn_filter_scripts(){
        wp_deregister_style('jetpack-widgets');
        wp_deregister_style('grunion.css'); // Grunion contact form
        wp_dequeue_style( 'jetpack-widget-social-icons-styles' );
        wp_dequeue_style( 'jetpack_css' );
        wp_deregister_style( 'jetpack_css' );
}

add_action( 'wp_enqueue_scripts', 'crunchify_enqueue_scripts_styles',100000000 );
function crunchify_enqueue_scripts_styles() {
     wp_dequeue_script( 'devicepx' );
}
```

Perhaps deregistering as well as dequeuing was a little overzealous 🤔

**Comment by johnbillion** [comment]
You don't need to build anything if you use the `develop` branch, the only thing that gets built in QM is the Sass, and that's currently committed directly to the repo too because I know people are using clones of the repo directly.

Thanks for that code block. I imagine the problem lies somewhere among the deregistering and dequeueing - I'll find some time over the next couple of weeks to take a look.

**Comment by johnbillion** [comment]
Gonna close this off, please do re-open if you can figure out what caused this or if you can reproduce. Cheers!

**Comment by johnbillion** [comment]
Oh wait, I should read my own comments before closing tickets. This is with me.
