### ISSUE TITLE
Uncaught TypeError when adding class to body

### ISSUE THREAD

**Issue by thetwopct** [johnbillion/query-monitor#466]
I'm adding classes to my body via functions.php with the following code:

```
function my_plugin_body_class($classes) {
if (is_archive('team')) {
    return array_merge( $classes, array( 'modal-animation' ) );
}
}
add_filter('body_class', 'my_plugin_body_class');
```

But when this is activated and QM is activated, I get the following error: 

```
Fatal error: Uncaught TypeError: Argument 1 passed to QM_Collector_Theme::filter_body_class() must be of the type array, null given, called in /Users/me/Sites/mysite/wp-includes/class-wp-hook.php on line 288 and defined in /Users/me/Sites/mysite/wp-content/plugins/query-monitor/collectors/theme.php:143
Stack trace:
#0 /Users/me/Sites/mysite/wp-includes/class-wp-hook.php(288): QM_Collector_Theme->filter_body_class(NULL)
#1 /Users/me/Sites/mysite/wp-includes/plugin.php(208): WP_Hook->apply_filters(NULL, Array)
#2 /Users/me/Sites/mysite/wp-includes/post-template.php(843): apply_filters('body_class', Array, Array)
#3 /Users/me/Sites/mysite/wp-includes/post-template.php(602): get_body_class(Array)
#4 /Users/me/Sites/mysite/wp-content/themes/mytheme/header.php(19): body_class()
#5 /Users/me/Sites/mysite/wp-includes/template.php(722): require_once('/Users/james/Si...')
#6 /Users/me/Sites/mysite/wp-includes/template.php in /Users/me/Sites/mysite/wp-content/plugins/query-monitor/collectors/theme.php on line 143

```

I'm guessing its my code problem rather than a plugin problem, but couldn't find similar problems online so thought I'd raise it. Thanks! 🙏

**Comment by thetwopct** [comment]
I'm a doughnut. My code 😂

```
function my_plugin_body_class($classes) {
if (is_archive('team')) {
    $classes[] = 'modal-animation';
}
return $classes;
}
add_filter('body_class', 'my_plugin_body_class');
```
