### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by hogash** [johnbillion/query-monitor#841]
Hey!

I'm sometimes getting this error below, however I'm not entirely sure when. I believe when I'm inside Customizer.

```
PHP Fatal error:  Uncaught TypeError: parse_url(): Argument #1 ($url) must be of type string, bool given in /../wp-content/plugins/query-monitor/collectors/http.php:374
Stack trace:
#0 /../wp-content/plugins/query-monitor/collectors/http.php(374): parse_url(false, 1)
#1 /../wp-content/plugins/query-monitor/classes/Collectors.php(84): QM_Collector_HTTP->process()
#2 /../wp-content/plugins/query-monitor/classes/Dispatcher.php(108): QM_Collectors->process()
#3 /../wp-content/plugins/query-monitor/dispatchers/Html.php(352): QM_Dispatcher->get_outputters('html')
#4 /../wp-content/plugins/query-monitor/dispatchers/Html.php(316): QM_Dispatcher_Html->before_output()
#5 /../wp-includes/class-wp-hook.php(324): QM_Dispatcher_Html->dispatch('')
#6 /../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /../wp-includes/load.php(1260): do_action('shutdown')
#9 [internal function]: shutdown_action_hook()
#10 {main}
  thrown in /../wp-content/plugins/query-monitor/collectors/http.php on line 374
```

Looking at the code, I believe instead of..

```$host = (string) parse_url( $request['url'], PHP_URL_HOST );```

It should be..

```$host = parse_url( (string) $request['url'], PHP_URL_HOST );```

**Comment by johnbillion** [comment]
What's causing the `$url` parameter to be `false`?

**Comment by johnbillion** [comment]
Did you find anything from this @hogash ?

**Comment by hogash** [comment]
> Did you find anything from this @hogash ?

No, I didn't. Let's close the issue for the moment and get back in case that error returns. Thanks!
