### ISSUE TITLE
QM Drop-in issue with WP All Import plugin

### ISSUE THREAD

**Issue by shivapoudel** [johnbillion/query-monitor#847]
Let's replicate the bug.

1. Go to the "All Import > New Import" page.
2. Upload the "FRAGRANCEDIRECT_FRAGRANCE.csv" file provided above and select Create new "WooCommerce Products".
3. Continue to step 2 and again to step 3.
4. Just drag the "product_name" as a title for testing.
5. Continue to step 4 and the issue arises within "admin.php?page=pmxi-admin-import&action=options"
6. Hurray the issue arrived! Please note: db.php drop-in symlink file of Query monitor should reside in a wp-content directory to receive the bug.

```
[25-Jan-2024 05:46:53 UTC] PHP Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in D:\htdocs\shop-eachperson\app\public\wp-includes\functions.php:625
Stack trace:
#0 D:\htdocs\shop-eachperson\app\public\wp-includes\functions.php(625): serialize(Object(PMXI_Import_Record))
#1 D:\htdocs\shop-eachperson\app\public\wp-content\plugins\wp-all-import-pro\classes\session.php(83): maybe_serialize(Object(PMXI_Import_Record))
#2 D:\htdocs\shop-eachperson\app\public\wp-content\plugins\wp-all-import-pro\controllers\admin\import.php(1845): PMXI_Session->set('import', Object(PMXI_Import_Record))
#3 D:\htdocs\shop-eachperson\app\public\wp-content\plugins\wp-all-import-pro\wp-all-import-pro.php(773): PMXI_Admin_Import->options()
#4 D:\htdocs\shop-eachperson\app\public\wp-includes\class-wp-hook.php(324): PMXI_Plugin->adminInit('')
#5 D:\htdocs\shop-eachperson\app\public\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 D:\htdocs\shop-eachperson\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#7 D:\htdocs\shop-eachperson\app\public\wp-admin\admin.php(175): do_action('admin_init')
#8 {main}
thrown in D:\htdocs\shop-eachperson\app\public\wp-includes\functions.php on line 625
```

**Comment by johnbillion** [comment]
Thanks for the report Shiva!

I can't see anything in the stack trace that's specific to Query Monitor. Can you provide some more info please?

**Comment by shivapoudel** [comment]
@johnbillion Please install WP All Import plugins and Query Monitor with drop-in `db.php` enabled:
- [wpallimport-wp-all-import-pro-4.8.5.zip](https://composer.eachperson.com/dist/wpallimport/wp-all-import-pro/wpallimport-wp-all-import-pro-4.8.5.zip)
- [wpallimport-wpai-woocommerce-add-on-4.0.0.zip](https://composer.eachperson.com/dist/wpallimport/wpai-woocommerce-add-on/wpallimport-wpai-woocommerce-add-on-4.0.0.zip)

Now follow these steps to replicate the bug within WP All Importer:
- Go to the "**All Import > New Import**" page.
- Upload the "[sample_products.csv](https://github.com/woocommerce/woocommerce/raw/trunk/plugins/woocommerce/sample-data/sample_products.csv)" file and select Create new "WooCommerce Products".
- Continue to Step 2 and again click on Continue to Step 3.
- Just drag the "name" as a title for testing.
- Continue to Step 4 and the issue arises.

![image](https://github.com/johnbillion/query-monitor/assets/3774827/fd6158ca-7126-4176-b6f0-66399b7a0571)

When I remove the `db.php` drop-in everything works perfectly. Thinking so I contacted first to the WP All Import team but they said it's a known issue and I can report it here. Please lemme know if you need help replicating the issue.

**Comment by shivapoudel** [comment]
@johnbillion Just a follow-up! Did you replicated the issue?
